version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: finwise-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: OnLvYZbPHjjMAYHKDQtBqewVKpdxpOlq
      POSTGRES_DB: railway
    ports:
      - "11726:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: